import type { Metadata } from "next";
import "./globals.css";
import NavBarComponent from "./components/NavBar";

import { Noto_Sans } from "next/font/google"; // You can choose any font
import FooterComponent from "./components/FooterComponent";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // Add other weights as needed
  variable: "--font-noto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.className}>
      <body>
        <NavBarComponent />

        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
